### PR TITLE
Do you have plan to add Super Game Boy "emulation" for Super Game Boy enhanced Game Boy games

### PR DESCRIPTION
**Pull request by ghost**
@bardeci @hi-ban In Options > System > Emulated Hardware

> Auto
> GB
> **SGB**
> **SGB2**
> GBC
> GBA

SGB emulation mode is for **Super Game Boy enhanced Original Game Boy games: SGB Borders, SGB Color Palettes**

SGB Enhanced for example: Kirby's Dream Land 2 (GB) (SGB Enhanced), Mega Man V (GB) (SGB Enhanced), Donkey Kong 94' (GB) (SGB Enhanced), ect...

Game Boy emulation
Mega Man V (U)  S ! _1659195683405

Super Game Boy emulation
Mega Man V (U)  S ! _1659195723044

Super Game Boy emulation with SGB Borders
Mega Man V

SNES Nintendo Super Game Boy border - **SGB** emulation
Super Game Boy

SNES Nintendo Super Game Boy 2 border - **SGB2** emulation
Super Game Boy 2

File extension: .sgb

### CODE REVIEW

**Comment by MCPE22** [comment]
Super Game Boy mode: Super Game Boy Border
SGB
Super Game Boy 2 mode: Super Game Boy 2 Border
SGB2

**Comment by MCPE22** [comment]
Do you have plan?

**Comment by bardeci** [comment]
Nope, there are no plans for that. Sorry.

**Comment by ghost** [comment]
No plans. Requires SNES Emulation. I can use endrift's mGBA emulator instead

**Pull request closed without merging**
